### ISSUE TITLE
autocomplete not working

### ISSUE THREAD

**Issue by rrrfffrrr** [Hanul/UUI#1]
in [UUI/UUI/BROWSER/FULL_INPUT.js](https://github.com/Hanul/UUI/blob/master/UUI/BROWSER/FULL_INPUT.js
)

autocomplete:'off' is not working

**Comment by Hanul** [comment]
UPPERCASE를 `git pull` 명령어로 업데이트 하시고, UUI 또한 업데이트 하신 후 `isOffAutocomplete`를 `true`로 설정하시면 됩니다.

**Comment by rrrfffrrr** [comment]
![autocomplete](https://cloud.githubusercontent.com/assets/11633118/15711939/39dce436-284b-11e6-9177-6b6e3b6eeed0.png)

i tried that but not working

`isOffAutocomplete : true`

**Comment by Hanul** [comment]
UUI 패키징을 안했군요. 지금 해서 올렸습니다. UUI를 BOX에 넣어주세요.

**Comment by rrrfffrrr** [comment]
Even following your suggestion, autocomplete is still working.

I tested next following code.

`TD({
							c : UUI.FULL_INPUT({
								inputStyle : {
									color : '#fff',
									autocomplete : 'off'
								},
								style : {
									backgroundColor : '#161616',
									borderTop : '1px solid #fff'
								},
								name : 'content',
								placeholder : '메세지를 입력하세요.',
								isOffAutocomplete : true
							})
						}),`

in the html,

`<input style="position: absolute; left: 0px; top: 0px; width: 100%; border: medium none; background: transparent none repeat scroll 0% 0%; color: rgb(255, 255, 255);" placeholder="메세지를 입력하세요." name="content">`

is created.

**Comment by Hanul** [comment]
UUI를 업뎃하셔서 해결되셔씀
